# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AUXSmartHome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for AUXSmartHome
  #pod 'RTRootNavigationController', ‘0.6.4’
  #pod "IQKeyboardManager"
  pod 'Toast', ‘4.0.0’

  pod 'QMUIKit', ‘2.9.3’
  pod 'MBProgressHUD', ‘1.1.0’
  pod 'AFNetworking', ‘3.2.1’
  pod 'YYModel', ‘1.0.4’
  pod 'MagicalRecord', ‘2.3.2’
  pod 'JPush', ‘3.1.2’
  pod 'Bugly', ‘2.5.0’
  pod 'SDWebImage', ‘4.4.6’
  pod 'MessageThrottle', ‘1.3.2’
  
  pod 'UMCCommon', ‘2.0.1’
  pod 'UMCAnalytics', ‘6.0.3’
  pod 'UMCErrorCatch', ‘1.0.0’

  pod 'WechatOpenSDK', ‘1.8.4’
  
  pod 'AMapSearch', ‘6.6.0’
  pod 'AMap2DMap'
  pod 'AMapLocation', ‘2.6.1’
  
  pod 'MJRefresh'

end

target 'AUXTodayExtension' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for AUXSmartHome
    pod 'MBProgressHUD', ‘1.1.0’
    pod 'AFNetworking', ‘3.2.1’
    pod 'YYModel', ‘1.0.4’
    pod 'SDWebImage', ‘4.4.6’
    pod 'UMCAnalytics', ‘6.0.3’
    pod 'JPush', ‘3.1.2’
end
